FROM nginx:alpine
COPY src/main/resources/nginx/nginx.conf /etc/nginx/nginx.conf
COPY src/main/resources/nginx/sites-enabled/load-balancer.conf /etc/nginx/sites-enabled/load-balancer.conf
EXPOSE 80 443