FROM nginx:alpine

# Instalar certbot e certbot-nginx
RUN apk add --no-cache certbot certbot-nginx

# Copiar configurações do nginx
COPY src/main/resources/nginx/nginx.conf /etc/nginx/nginx.conf
COPY src/main/resources/nginx/sites-enabled/load-balancer-teste.conf /etc/nginx/sites-enabled/load-balancer.conf

# Criar diretórios necessários para certificados
RUN mkdir -p /etc/letsencrypt/live

EXPOSE 80 443