spring:
  application:
    name: pork

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: 'health'
    endpoint:
      health:
        show-details: always
        show-components: always
    health:
      db:
        enabled: true

jwt:
  secret: ${SPRING_SECRET}

url:
  link: ${URL_AUTH}
  redefinir-senha: ${REDEFINIR_SENHA_URL}
  verificar-conta: ${VERIFICAR_CONTA_URL}

server:
  port: 8080

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    com.devchaves.Pork_backend: DEBUG