CREATE TABLE tb_password_token (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    token VARCHAR(255) NOT NULL,

    user_id BIGINT NOT NULL,

    criado_em TIMESTAMP NOT NULL,

    expira_em TIMESTAMP NOT NULL,

    expirado BOOLEAN NOT NULL,

    CONSTRAINT fk_password_token_user
        FOREIGN KEY (user_id)
        REFERENCES tb_user(id)
        ON DELETE CASCADE
);
