name: ci/cd pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up JDK 21
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot JAR
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pork:latest .

      - name: Login no Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pork:latest

      - name: Deploy na VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
                  docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pork:latest
                  docker stop pork || true
                  docker rm pork || true
                  docker run -d --name pork -p 8080:8080 --env-file /caminho/.env ${{ secrets.DOCKERHUB_USERNAME }}/pork:latest
